version: '3.8'

services:
  random-toolbox-dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: random-toolbox-dev
    ports:
      - "5600:5600"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
      - PORT=5600
    volumes:
      # Mount source code for development
      - ./src:/app/src:rw
      - ./tests:/app/tests:rw
      - ./logs:/app/logs
    restart: unless-stopped
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5600", "--debug"]
    networks:
      - random-toolbox-dev-network

  # Optional: Add testing service
  random-toolbox-test:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: random-toolbox-test
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
      - ./pytest.ini:/app/pytest.ini:ro
    command: ["python", "-m", "pytest", "tests/", "-v"]
    networks:
      - random-toolbox-dev-network
    profiles: ["test"]

networks:
  random-toolbox-dev-network:
    driver: bridge
    name: random-toolbox-dev-net